import type { PortfolioStartup } from "../models/portfolio";

export const MOCK_PORTFOLIO: PortfolioStartup[] = [
  {
    id: "1",
    operationalName: "NeuraX",
    description:
      "AI-powered early cancer detection platform utilizing proprietary radiology datasets.",
    targetMarkets: ["Healthtech", "Generative AI"],
    businessCategory: "Healthcare",
    employeeCount: 45,
    foundedYear: 2021,
    countryName: "Romania",
    regionName: "Europe",
    peerScore: 94,
    currentValuation: "$12M",
    sentiment: 87,
    sentimentTrend: 4,
    sentimentHistory: [
      { month: "J", value: 30 },
      { month: "F", value: 25 },
      { month: "M", value: 40 },
      { month: "A", value: 45 },
      { month: "M", value: 50 },
      { month: "J", value: 55 },
      { month: "J", value: 58 },
      { month: "A", value: 62 },
      { month: "S", value: 68 },
      { month: "O", value: 72 },
      { month: "N", value: 78 },
      { month: "D", value: 87 },
    ],
    savedAt: "2025-02-10T12:00:00Z",
  },
  {
    id: "2",
    operationalName: "SolarGrid",
    description:
      "Decentralized energy trading platform connecting solar panel owners with local energy markets using blockchain-based smart contracts.",
    targetMarkets: ["CleanTech", "Energy", "Blockchain"],
    businessCategory: "Energy",
    employeeCount: 32,
    foundedYear: 2022,
    countryName: "Germany",
    regionName: "Europe",
    peerScore: 81,
    currentValuation: "$8.5M",
    sentiment: 72,
    sentimentTrend: -2,
    sentimentHistory: [
      { month: "J", value: 60 },
      { month: "F", value: 65 },
      { month: "M", value: 70 },
      { month: "A", value: 75 },
      { month: "M", value: 80 },
      { month: "J", value: 78 },
      { month: "J", value: 76 },
      { month: "A", value: 74 },
      { month: "S", value: 73 },
      { month: "O", value: 74 },
      { month: "N", value: 73 },
      { month: "D", value: 72 },
    ],
    savedAt: "2025-01-28T09:30:00Z",
  },
  {
    id: "3",
    operationalName: "FinLedger",
    description:
      "Real-time financial compliance monitoring for fintechs and neobanks, automating KYC/AML workflows with explainable AI.",
    targetMarkets: ["Fintech", "RegTech"],
    businessCategory: "Financial Services",
    employeeCount: 58,
    foundedYear: 2020,
    countryName: "United Kingdom",
    regionName: "Europe",
    peerScore: 88,
    currentValuation: "$22M",
    sentiment: 91,
    sentimentTrend: 6,
    sentimentHistory: [
      { month: "J", value: 55 },
      { month: "F", value: 58 },
      { month: "M", value: 62 },
      { month: "A", value: 66 },
      { month: "M", value: 70 },
      { month: "J", value: 74 },
      { month: "J", value: 78 },
      { month: "A", value: 80 },
      { month: "S", value: 83 },
      { month: "O", value: 86 },
      { month: "N", value: 89 },
      { month: "D", value: 91 },
    ],
    savedAt: "2025-02-14T15:45:00Z",
  },
  {
    id: "4",
    operationalName: "AgriSense",
    description:
      "Precision agriculture platform using satellite imagery and IoT sensors to optimize crop yields and reduce water consumption by up to 40%.",
    targetMarkets: ["AgriTech", "IoT", "Sustainability"],
    businessCategory: "Agriculture",
    employeeCount: 27,
    foundedYear: 2023,
    countryName: "Netherlands",
    regionName: "Europe",
    peerScore: 76,
    currentValuation: "$4.2M",
    sentiment: 65,
    sentimentTrend: 8,
    sentimentHistory: [
      { month: "J", value: 20 },
      { month: "F", value: 25 },
      { month: "M", value: 30 },
      { month: "A", value: 35 },
      { month: "M", value: 40 },
      { month: "J", value: 42 },
      { month: "J", value: 48 },
      { month: "A", value: 50 },
      { month: "S", value: 55 },
      { month: "O", value: 58 },
      { month: "N", value: 62 },
      { month: "D", value: 65 },
    ],
    savedAt: "2025-02-01T08:15:00Z",
  },
  {
    id: "5",
    operationalName: "EduPath",
    description:
      "Adaptive learning platform that personalizes K-12 curricula using cognitive science models and real-time student performance analytics.",
    targetMarkets: ["EdTech", "AI"],
    businessCategory: "Education",
    employeeCount: 40,
    foundedYear: 2019,
    countryName: "France",
    regionName: "Europe",
    peerScore: 83,
    currentValuation: "$15M",
    sentiment: 79,
    sentimentTrend: 1,
    sentimentHistory: [
      { month: "J", value: 70 },
      { month: "F", value: 72 },
      { month: "M", value: 73 },
      { month: "A", value: 74 },
      { month: "M", value: 75 },
      { month: "J", value: 76 },
      { month: "J", value: 76 },
      { month: "A", value: 77 },
      { month: "S", value: 77 },
      { month: "O", value: 78 },
      { month: "N", value: 78 },
      { month: "D", value: 79 },
    ],
    savedAt: "2025-01-15T11:00:00Z",
  },
];
