export const TARGET_MARKETS = [
	"healthcare",
	"information technology",
	"education",
	"financial services",
	"retail",
	"technology",
	"manufacturing",
	"government",
	"business services",
	"telecommunications",
	"e-commerce",
	"construction",
	"real estate",
	"automotive",
	"hospitality",
	"cloud computing",
	"logistics",
	"energy",
	"digital services",
	"cybersecurity",
	"public sector",
	"transportation",
	"insurance",
	"food and beverage",
	"finance",
	"agriculture",
	"marketing",
	"human resources",
	"entertainment",
	"industrial",
	"fintech",
];
