import type { Startup } from "../models/startup";

export const MOCK_STARTUPS: Startup[] = [
  {
    id: "1",
    name: "NeuralFlow AI",
    description: "AI-powered diagnostics for early cancer detection using radiology data.",
    industry: "Healthtech",
    fundingStage: "Generative AI",
    teamSize: 12,
    location: "San Francisco, CA",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop",
    founderName: "John Doe",
    bullBearScore: 82,
    bullBearSentiment: "Very Bullish",
    peerScore: 94,
    mrr: 83000,
    ticketSize: 12000000,
    countryCode: "US",
  },
  {
    id: "2",
    name: "GreenCycle",
    description: "IoT-enabled smart recycling infrastructure for sustainable urban development.",
    industry: "CleanTech",
    fundingStage: "Seed",
    teamSize: 8,
    location: "Berlin, Germany",
    imageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&h=600&fit=crop",
    founderName: "Anna Schmidt",
    bullBearScore: 76,
    bullBearSentiment: "Bullish",
    peerScore: 88,
    mrr: 45000,
    ticketSize: 5000000,
    countryCode: "DE",
  },
  {
    id: "3",
    name: "HealthBridge",
    description: "AI-matched telehealth platform connecting patients with specialized providers.",
    industry: "HealthTech",
    fundingStage: "Series B",
    teamSize: 45,
    location: "Boston, MA",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop",
    founderName: "Sarah Johnson",
    bullBearScore: 91,
    bullBearSentiment: "Very Bullish",
    peerScore: 92,
    mrr: 250000,
    ticketSize: 25000000,
    countryCode: "US",
  },
  {
    id: "4",
    name: "FinFlow",
    description: "Modern banking infrastructure bridging traditional finance with Web3.",
    industry: "FinTech",
    fundingStage: "Series A",
    teamSize: 28,
    location: "London, UK",
    imageUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=600&fit=crop",
    founderName: "James Porter",
    bullBearScore: 85,
    bullBearSentiment: "Very Bullish",
    peerScore: 90,
    mrr: 180000,
    ticketSize: 18000000,
    countryCode: "GB",
  },
  {
    id: "5",
    name: "EduVerse",
    description: "Immersive VR education platform transforming learning experiences worldwide.",
    industry: "EdTech",
    fundingStage: "Seed",
    teamSize: 15,
    location: "Austin, TX",
    imageUrl: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=800&h=600&fit=crop",
    founderName: "Mike Chen",
    bullBearScore: 79,
    bullBearSentiment: "Bullish",
    peerScore: 86,
    mrr: 62000,
    ticketSize: 8000000,
    countryCode: "US",
  },
  {
    id: "6",
    name: "FoodChain",
    description: "Blockchain-powered supply chain transparency from farm to table.",
    industry: "FoodTech",
    fundingStage: "Pre-Seed",
    teamSize: 6,
    location: "Amsterdam, Netherlands",
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=600&fit=crop",
    founderName: "Lars van Berg",
    bullBearScore: 72,
    bullBearSentiment: "Bullish",
    peerScore: 81,
    mrr: 28000,
    ticketSize: 3000000,
    countryCode: "NL",
  },
  {
    id: "7",
    name: "SpaceLogix",
    description: "Autonomous drone delivery optimization reducing last-mile carbon footprint.",
    industry: "Logistics",
    fundingStage: "Series A",
    teamSize: 32,
    location: "Singapore",
    imageUrl: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&h=600&fit=crop",
    founderName: "Wei Zhang",
    bullBearScore: 88,
    bullBearSentiment: "Very Bullish",
    peerScore: 93,
    mrr: 195000,
    ticketSize: 20000000,
    countryCode: "SG",
  },
  {
    id: "8",
    name: "CloudForge",
    description: "Global edge network infrastructure with zero-config deployment architecture.",
    industry: "DevTools",
    fundingStage: "Seed",
    teamSize: 18,
    location: "Remote",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop",
    founderName: "Alex Rivera",
    bullBearScore: 83,
    bullBearSentiment: "Very Bullish",
    peerScore: 89,
    mrr: 110000,
    ticketSize: 10000000,
    countryCode: "US",
  },
];
